apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "project-argus-monitor.fullname" . | quote }}
  labels:
    {{- include "project-argus-monitor.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "true"
            proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: monitor
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python"]
            args: ["monitor.py"]
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: URLS_TO_MONITOR
              value: {{ .Values.urls | quote }}
            - name: AWS_REGION
              value: "us-east-1"
            envFrom:
            - secretRef:
                name: aws-creds
          restartPolicy: OnFailure