name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  # --- JOB 1: THE SAFETY CHECKS (CI) ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Use the dev file so we get pytest and respx!
          pip install -r requirements-dev.txt

      - name: Check Formatting (Black)
        run: black --check monitor.py test_monitor.py

      - name: Run Linter (Flake8)
        run: flake8 monitor.py test_monitor.py

      - name: Run Unit Tests (Pytest)
        run: pytest test_monitor.py

      - name: Terraform Security Scan (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.0

  # --- JOB 2: THE DEPLOYMENT (CD) ---
  deploy:
    needs: test # THIS IS THE GATE: Only run if 'test' passes!
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: project-argus-monitor
          IMAGE_TAG: ${{ github.sha }} # USE THE UNIQUE COMMIT ID
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name argus-monitor-function \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/argus-monitor:${{ github.sha }}